### ISSUE TITLE
Exporting region problem

### ISSUE THREAD

**Issue by lesolorzanov** [TissUUmaps/TissUUmapsCore#10]
When I try to export the csv containg the data of a region I get an error in the browser

```
Uncaught InternalError: allocation size overflow
    pointsInRegionsToCSV https://tissuumaps.research.it.uu.se/video/js/utils/regionUtils.js:1123
    registerActions https://tissuumaps.research.it.uu.se/video/js/tmapp.js:31
```
It's very few points in space but it has maybe some 100 features associated to it.

I reduced the features to maybe 20 and then it managed to save a csv after a long time and it contained incorrect information. For example, I have a global ID that is an integer, and it was saved as a float and the number was lost, it was a column full of 0.0.

One field that caused trouble (I dont know why) is that I have a string in it, containing a stringified json. And when that filed is present, even thought it is a string, the csv sometimes exported, sometimes, not. 

And lastly sometimes the export contains a weird new column that the original data doesn't have. It looks like the response type of an http request it starts with:
data:text/csv;base64 and then a super long hexstring that mightbe the csv itself, so theres a csv within the csv. Or something like that

**Comment by cavenel** [comment]
Thank you @zloysmiertniy, could you maybe share an example of a csv file that fails?

**Comment by FredrikNysjo** [comment]
Exporting regions to CSV has been improved in commit cddd4be . The memory usage is still an issue, but since that would require larger changes to address I am closing this issue for now.
