### ISSUE TITLE
Region interface and js console

### ISSUE THREAD

**Issue by zloysmiertniy** [TissUUmaps/TissUUmapsCore#11]
In the view of the regions, when a name is undefined maybe it's better just to not show the column instead of showing a column with many "undefined" printed.

Also there are too many console.log calls in regionutils:1004 and 1014, please don't include them in released versions it's only for debugging.

**Comment by cavenel** [comment]
Thanks @zloysmiertniy!
I will close this for now, as debugging console logs have been removed in https://github.com/TissUUmaps/TissUUmapsCore/commit/b660d2dd418c685afca846727f37bc0a9e35b345.

For the view of regions without names, it is a bit more difficult as sometimes you have a mix of regions with and without names, I think we will leave it like this for uniformity.
