### ISSUE TITLE
Loading consecutive CSV files with no background image makes incorrect viewer dimensions

### ISSUE THREAD

**Issue by kaizen89** [TissUUmaps/TissUUmapsCore#12]
Hi,
I am running tissuMaps on windows, I am only using a cell coordinates and marker file. It was working smoothly but when I tried with a file generated from a whole slide image, was not able to display all the cells even after zooming out to 100%.

plot displaying all the cells in R
![image](https://user-images.githubusercontent.com/30392707/152992191-75d9aed8-55d5-4eb3-b9e2-eec440578b09.png)

Cells displayed in tissuMaps
![image](https://user-images.githubusercontent.com/30392707/152992260-7a84366e-43d2-4add-a96c-9fa52e288ee6.png)

Also, even when all the cells are displayed, when zooming, cells on left or right are masked as if zooming was only possible in the center of the plot.

**Comment by kaizen89** [comment]
Sure! Here's a folder where you can find 2 files for which I noticed this issue. [https://www.dropbox.com/sh/foqwe18oq24ddie/AAB7FCPOvuEOMtmpAAN4Ii1ha?dl=0](url)
Yes, I'm using the windows installer, the latest version 3.0.5.3.

Thanks!

**Comment by kaizen89** [comment]
Ah I see! I confirm that it works when closing and reopening. Thanks a lot!

**Comment by cavenel** [comment]
I will reopen this, as it would be good to be able to load successive CSV files without reloading the software.

**Comment by cavenel** [comment]
Fixed in https://github.com/TissUUmaps/TissUUmapsCore/commit/7919e7d33681a5e7f39e99c3c8d2fef1eeb9da30
Now it reloads the file with correct dimensions.
Should be fixed from [version 3.0.5.7](https://github.com/TissUUmaps/TissUUmaps/releases/tag/3.0.5.7)
