### ISSUE TITLE
Drawing regions seem to bugged

### ISSUE THREAD

**Issue by vahvero** [TissUUmaps/TissUUmapsCore#2]
Hello!

When serving locally from a deep zoom image the `example.html`
the region drawing seems to have some issues.

![Screenshot from 2021-06-10 16-36-40](https://user-images.githubusercontent.com/30704280/121534707-1ffba000-ca0a-11eb-91cd-1648ebbc2d43.png)

I have changed the script in the bottom part to

```
<script>

    document.getElementById("project_title").innerText = "Project title";
    // ----------
    $(document).ready(function () {

        tmapp.fixed_file = "dzi_images/dzi_test.dzi";
        tmapp.slideFilename = "dzi_test"
	    tmapp.layers =[
            {
                name:"Density",
                tileSource:"dzi_images/dzi_test_dens.dzi"}, 
            {
                name: "Class", 
                tileSource:"dzi_images/dzi_test_clf.dzi"
            }
        ];
        
        tmapp.registerActions();
        tmapp.init();
    });

</script>
```

And cannot draw any regions. Is there something I have missed?

**Comment by cavenel** [comment]
Hi,

Can you test with the file "example_reorg.html" instead of "example.html"?
I just realized that we need to clean these files and keep only one example (that will be example_reorg.html), I will push that soon.

About drawing regions, it draws by clicking points one after the other.

**Comment by vahvero** [comment]
Okey, this `example_reorg.html` file seems to work ok!

![Screenshot from 2021-06-11 10-42-31](https://user-images.githubusercontent.com/30704280/121650079-e24a5600-caa1-11eb-9589-47f755001c0c.png)

I have some already regions premarked and try to reverse engineer the `region.json` import. Thank you!
